language: go

go:
  - 1.13

if: branch IN (version-checker, repo-creator)

script:
  - make clean
  - |
    case "$TRAVIS_BRANCH" in
      version-checker)
        # Travis uses a shallow clone with `--depth=50`, so we need to fetch all remote tags by ourselves.
        git fetch --tags
        make check_new_versions
        ;;
      repo-creator)
        make create_repositories
        ;;
    esac
